### ISSUE TITLE
If there is a way to run the project locally

### ISSUE THREAD

**Issue by suedar** [vue-microfrontends/dogs-dashboard#2]
<img width="521" alt="error" src="https://user-images.githubusercontent.com/18492953/81648414-3f1fab00-9461-11ea-81c0-7b0111a808e1.png">

Hey, I want to know if there is a way to run the sub-spa-project locally without put it into the whole project.
Like this project, when I run `npm run serve`, I got this error.

Thanks for ur help.
:)

**Comment by suedar** [comment]
It seems that I have to create another `main.dev.js` file and change webpack config.

**Comment by joeldenning** [comment]
Generally we encourage running the microfrontends as instructed in the readme, instead of running them independently. This is because it is possible to have cross-microfrontend imports that fail when one app is run standalone. Another reason is that it is difficult to maintain two separate ways to do local development, and is frustrating when something works as a standalone app but is broken when integrated with other microfrontends.

**Comment by suedar** [comment]
No offence. Actualy I think that micro-frontend is meant to set the sub-project individually. So maybe in the ideal case, the sub-project is able to run independently ?
